name: freebsd

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
    contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      uses: vmactions/freebsd-vm@v1.0.8
      with:
        prepare: |
          pkg install -y \
            devel/check \
            devel/git \
            devel/pkgconf
        run: |
          make
          make test
