name: macos

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
    contents: read

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
    - name: install check
      run: brew install check
    - name: run tests
      run: make test
