name: openbsd

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
    contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      uses: vmactions/openbsd-vm@v1.0.8
      with:
        prepare: |
          pkg_add \
            check \
            git \
            pkgconf
        run: |
          make
          make test
