[package]
name = "iodine-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1.51", features = ["full"] }
nix = { version = "0.31", features = ["user", "fs"] }
libc = "0.2"
bytes = "1.11"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
md-5 = "0.11"
data-encoding = "2.10"
data-encoding-macro = "0.1"
thiserror = "2"
lru = "0.16"
tun = { version = "0.8", features = ["async"] }
flate2 = "1.1.9"
